export default {
  // SIGNIN
  SIGNIN_LOADING: 'SIGNIN_LOADING',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  // SIGNUP
  SIGNUP_LOADING: 'SIGNUP_LOADING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  // SIGNOUT
  SIGNOUT_LOADING: 'SIGNOUT_LOADING',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_ERROR: 'SIGNOUT_ERROR',
  TRY_SIGNIN: 'TRY_SIGNIN',
  REQUEST_LOADING: 'REQUEST_LOADING',
  REQUEST_FINISHED: 'REQUEST_FINISHED',
  //STORE USER
  STORE_USER: 'STORE_USER',
  CLEAR_ERROR: 'CLEAR_ERROR',
};
