export default {
  ADD_PIN: 'ADD_PIN',
  UPDATE_PIN: 'UPDATE_PIN',
  VALID_PIN: 'VALID_PIN',
  REQUEST_LOADING: 'REQUEST_LOADING',
  REQUEST_FINISHED: 'REQUEST_FINISHED',
  SHOW_TEXT_BACKUP_SEED: 'SHOW_TEXT_BACKUP_SEED',
  CLOSE_TEXT_BACKUP_SEED: 'CLOSE_TEXT_BACKUP_SEED',
  SHOW_DIALOG_BACKUP_SEED: 'SHOW_DIALOG_BACKUP_SEED',
  CLOSE_DIALOG_BACKUP_SEED: 'CLOSE_DIALOG_BACKUP_SEED',
};
