export default {
  // SIGNIN
  SIGNIN_LOADING: 'SIGNIN_LOADING',
  SIGNIN_SUCCESS: 'SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'SIGNIN_ERROR',
  STORE_BALANCE: 'STORE_BALANCE',
  //PIN
  ADD_PIN: 'ADD_PIN',
  UPDATE_PIN: 'UPDATE_PIN',
  VALID_PIN: 'VALID_PIN',
  SHOW_TEXT_BACKUP_SEED: 'SHOW_TEXT_BACKUP_SEED',
  CLOSE_TEXT_BACKUP_SEED: 'CLOSE_TEXT_BACKUP_SEED',
  SHOW_DIALOG_BACKUP_SEED: 'SHOW_DIALOG_BACKUP_SEED',
  CLOSE_DIALOG_BACKUP_SEED: 'CLOSE_DIALOG_BACKUP_SEED',
  // SIGNUP
  SIGNUP_LOADING: 'SIGNUP_LOADING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_ERROR: 'SIGNUP_ERROR',
  // SIGNOUT
  SIGNOUT_LOADING: 'SIGNOUT_LOADING',
  SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
  SIGNOUT_ERROR: 'SIGNOUT_ERROR',
  TRY_SIGNIN: 'TRY_SIGNIN',
  //REQUEST
  REQUEST_LOADING: 'REQUEST_LOADING',
  REQUEST_FINISHED: 'REQUEST_FINISHED',
  //STORE USER
  STORE_USER: 'STORE_USER',
  CLEAR_ERROR: 'CLEAR_ERROR',
  //SEND PAYMENT
  RECEIVE_PAYMENT: 'RECEIVE_PAYMENT',
  COPY_ADDRESS: 'COPY_ADDRESS',
  CHOOSE_COINS: 'CHOOSE_COINS',
  //CONFIRMATION
  REQUEST_CODE_SUCCESS: 'SREQUEST_CODE_SUCCESS',
  REQUEST_CODE_ERROR: 'REQUEST_CODE_ERROR',
  CONFIRM_CODE_SUCCESS: 'CONFIRM_SUCCESS',
  CONFIRM_CODE_ERROR: 'CONFIRM_CODE_ERROR',
  CLEAR_INVALID_PHONENUMBER: 'CLEAR_INVALID_PHONENUMBER',
  SHOW_ERROR: 'SHOW_ERROR',
};
