# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LunesMobileWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LunesMobileWallet

  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNI18n', :path => '../node_modules/react-native-i18n'


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'SentryReactNative', :path => '../node_modules/react-native-sentry'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  target 'LunesMobileWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
