# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LunesMobileWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LunesMobileWallet

  #Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'LunesMobileWalletTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
