export default {
  TOKEN_VALIDATED: 'TOKEN_VALIDATED',
  USER_FETCHED: 'USER_FETCHED',
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  REQUEST_SIGNUP: 'REQUEST_SIGNUP',
  VALIDATE_TOKEN: 'VALIDATE_TOKEN',
  USER_LOGGED: 'USER_LOGGED',
  USER_LOGGED: 'USER_NOT_LOGGED',
};
