export default {
  REQUEST_LOADING: 'REQUEST_LOADING',
  REQUEST_FINISHED: 'REQUEST_FINISHED',
  // Request Code
  REQUEST_CODE_SUCCESS: 'SREQUEST_CODE_SUCCESS',
  REQUEST_CODE_ERROR: 'REQUEST_CODE_ERROR',
  // Confirm Code
  CONFIRM_CODE_SUCCESS: 'CONFIRM_SUCCESS',
  CONFIRM_CODE_ERROR: 'CONFIRM_CODE_ERROR',
};
